### ISSUE TITLE
ASTER band 8 - PredefinedWavelengths

### ISSUE THREAD

**Issue by samsammurphy** [robintw/Py6S#26]
ASTER band 8 in the PredefinedWavelengths class of wavelength.py does not seem to be correct. The Start Wavelength (2.25) is higher than the End Wavelength (2.244). 

(line 732 of wavelength.py)     ASTER_B8 = (-136, 2.250, 2.244)

The original 6S fortran code (attached) assigns the values of 2.21 and 2.39, respectively.
[ASTER.zip](https://github.com/robintw/Py6S/files/292396/ASTER.zip)

However, the 6S values are also odd. This is because the fortran array for the band 8 spectral filter function has 76 elements, yet the spectral range (2.39-2.21) divided by the spectral increment (0.0025) would require a 72 element array.

**Comment by robintw** [comment]
Thanks for noticing that!

I agree that the 6S values are odd, but I think it's probably best for Py6S to just use the 6S values (with a comment in the code indicating that they're odd).

If you want to submit a Pull Request, I'm happy for you to do so (it'd be a nice easy first PR), but otherwise I'm happy to make the change myself.

**Comment by samsammurphy** [comment]
Hi Robin,

**Comment by samsammurphy** [comment]
Thanks for you help with the PR

NB. the start and end wavelengths actually do correspond CORRECTLY with the 6S fortran code (i.e. I was mistaken previously because the Fortran code names the ASTER bands 3N and 3B .. as 3 and 4 .., this set me off by one)
